### ISSUE TITLE
Diff-Task

### ISSUE THREAD

**Issue by topa** [epha/robot#13]
A task, e.g. a npm script, which checks if something has changed since last run of a job/jobs could be useful.

**Comment by ephaee** [comment]
Related https://github.com/epha/robot/issues/1

**Comment by Jonas74** [comment]
Absolutely

**Comment by topa** [comment]
If checked the server responses for all 4 jobs:

**swissmedic**:

![swissmedic](https://cloud.githubusercontent.com/assets/1116484/7651965/daa35daa-fb06-11e4-9fbe-478a444ba29d.png)

**atc**: 

![atc](https://cloud.githubusercontent.com/assets/1116484/7651966/de90f152-fb06-11e4-8a3d-eba3c7f22be0.png)

**bag**

![bag](https://cloud.githubusercontent.com/assets/1116484/7651972/ec623a2a-fb06-11e4-96a2-c17c3f531f4f.png)

**kompendium**

![kompendium](https://cloud.githubusercontent.com/assets/1116484/7651978/f71d5814-fb06-11e4-9287-a9dad84bc3b0.png)

Only thing in common is `content-length`. So it is possible to compare server- and file-system-cotent-length. If file-system differs from server, file-system is outdated. I think this check should be fair-enough.

**Comment by topa** [comment]
There is the current sample implemantation for  ATC. https://github.com/epha/robot/blob/refactoring-step-1/bin/outdated.js
I think this code could be quite easy reused for ATC, BAG and Swissmedic. Kompendium will need a "Extrawurst".

**Comment by topa** [comment]
If you run

```
npm run outdated 
```

it will check which files needs to be updated and auto-start the particular jobs.
