### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by Jonas74** [epha/robot#19]
What value does the integration server add?

**Comment by topa** [comment]
The integration server imitates behavior of the real servers and it so able to help while development. 
For example, while refactoring you can change code often and test often. With other words: It speeds up development because it kills annoying waiting time for example, through network limitations (think of the kompendium download size).

**Comment by topa** [comment]
Another value - maybe a minor one - is that the server is some kind of documentation for the behavior we expect from the sites we parse.

**Comment by meaku** [comment]
Using a http-server and an URL as entry point makes the test more realistic and adds the benefit of testing all the http-fetching, url-resolving, unzipping implicit. Integration tests should be mocked as little as possible.

There are only two other options: 
- fetch from the real URL (which is fair enough, but takes way longer) 
- mock all function related to fetching the files (bad practice as it's no full integration anymore) 

Maybe we could run the tests against a fake server and the _real_ server to find out if the site breaks it or we have an internal logic error.

**Comment by topa** [comment]
I think that we agreed in the end that the integration-testing server helps a lot while development or rather is a development only topic. This means file contents consistency will be the next task.

**Comment by topa** [comment]
I really do not want to re-open this topic. However, this [article](http://www.heise.de/developer/artikel/Testautomatisierung-in-Legacy-Systemen-2670410.html) from heise developer may provide some comfort for both sides of our argument.
