### ISSUE TITLE
Cron-Job / robot-service

### ISSUE THREAD

**Issue by topa** [epha/robot#25]
There should be a cron-job or rather a "self-maintained" process that runs continuously all jobs after a certain amount of time. It should output if a job was triggered.

**Comment by topa** [comment]
I think we should talk of a robot-service, instead of a cronjob. If I understood this requirement right, "cronjob" should be a process that is running, instead of script that is triggered by the underlying OS.

I think there are some options how to solve this.

a) install a deamon globally like forever/pm2 on the machine, log the output somewhere and tail it
b) misuse module nodemon, install it as a package dependency, run a npm script, e.g. npm run robot-service (```{scripts: "robot-service": nodemon ./bin/cronjob}```). This will restart the script if it crashes.
c) just a npm script that starts the cronjob, but with the trait-off that when the script dies to process is gone

@meaku do you have any thoughts about this?

**Comment by topa** [comment]
I ran option c) the whole day and didn't crash, however there were only one change today. 
But there were this ominous debugging output from superagent (#21):

> double callback! 

This will need some investigations.

**Comment by meaku** [comment]
Option c) is not a bad choice. But auto restarting might be helpful. 
How about using pm2 programmatically. So you can have an npm script which starts the script supervised by pm2 like the following: 

```javascript
var pm2 = require('pm2');

pm2.connect(function() {
  pm2.start({
    script    : 'app.js',         // Script to be run
    exec_mode : 'cluster',        // Allow your app to be clustered
    instances : 4,                // Optional: Scale your app by 4
    max_memory_restart : '100M'   // Optional: Restart your app if it reaches 100Mo
  }, function(err, apps) {
    pm2.disconnect();
  });
});
``` 

See https://github.com/Unitech/pm2

**Comment by topa** [comment]
Current state:

just do `npm run robot-service`. This looks at the moment like the following:

```bash
npm run robot-service

> epha-robot@0.2.39 robot-service /SOME/PATH/TO/LOCAL/REPO
> node ./bin/service.js

cronjob Start Outdated Check
epha-robot@0.2.39 |  INFO |  ATC Check if /Users/topa/Workspace/epha/robot/data/auto/atc/atc.zip exists.
epha-robot@0.2.39 |  INFO |  BAG Check if /Users/topa/Workspace/epha/robot/data/auto/bag/XMLPublications.zip exists.
epha-robot@0.2.39 |  INFO |  Swissmedic Check if /Users/topa/Workspace/epha/robot/data/auto/swissmedic/swissmedic.xlsx exists.
epha-robot@0.2.39 |  INFO |  Kompendium Check if /Users/topa/Workspace/epha/robot/data/auto/kompendium/kompendium.zip exists.
epha-robot@0.2.39 |  INFO |  ATC Read and fetch file stats from disk and server.
epha-robot@0.2.39 |  INFO |  BAG Read and fetch file stats from disk and server.
epha-robot@0.2.39 |  INFO |  Swissmedic Read and fetch file stats from disk and server.
epha-robot@0.2.39 |  INFO |  Kompendium Read and fetch file stats from disk and server.
epha-robot@0.2.39 |  INFO |  ATC Fetched file stats from server.
epha-robot@0.2.39 |  INFO |  ATC Comparing disk and server stats now.
epha-robot@0.2.39 | DEBUG |  ATC File on disk is up-to-date
epha-robot@0.2.39 |  INFO |  BAG Fetched file stats from server.
epha-robot@0.2.39 |  INFO |  BAG Comparing disk and server stats now.
epha-robot@0.2.39 | DEBUG |  BAG File on disk is up-to-date
epha-robot@0.2.39 |  INFO |  Swissmedic Fetched file stats from server.
epha-robot@0.2.39 |  INFO |  Swissmedic Comparing disk and server stats now.
epha-robot@0.2.39 | DEBUG |  Swissmedic File on disk is up-to-date
epha-robot@0.2.39 |  INFO |  Kompendium Fetched file stats from server.
epha-robot@0.2.39 |  INFO |  Kompendium Comparing disk and server stats now.
epha-robot@0.2.39 | DEBUG |  Kompendium File on disk is up-to-date
epha-robot@0.2.39 |  WARN |  cronjob Outdated Check Finished
```

Seems like there is a problem with ```epha-logger```or with my configuration:

```javascript
var log = require("epha-log")({
  service: robot.name,
  version: robot.version,
  transports: [{ level: ["ERROR", "WARN"] }],
  type: "module"
});
```

@ephaee, @Jonas74 any ideas?

**Comment by topa** [comment]
I'll try to implement PM2 time-boxed, to solve auto-restarting after a crash.

**Comment by topa** [comment]
PM2 and also forever have both the same "problem", they swallow the `stdout`. But that is what we want to see. Surely you can define where PM2 should put it's log into a place where you just can `tail -f` it. Still, it is some kind of a workaround to use such tool a with `npm`. I think if you really need a process watcher, you should use it as it is meant: a global installed tool. 
Let's stick with option c) for now.
