### ISSUE TITLE
Data validation

### ISSUE THREAD

**Issue by topa** [epha/robot#26]
Basically most of the data in release, e.g. swissmedic.json, are collections containing key-value-objects.
So we should be able to describe them with a schema. By schema I think of a definition that describes how such a key-value-object does look like. It should be also possible to validate against these schema.

There is [hapijs/joi](https://github.com/hapijs/joi), which is a pretty widely used module: [41249 downloads in the last week](https://www.npmjs.com/search?q=joi). It describes itself as 

> Object schema description language and validator for JavaScript objects.

A schema for swissmedic.json could look like this:

```javascript
// array containing all known atc-codes
var atcCodes = require("data/release/atc/atcCodes.json");
var Joi = require("joi");

var swissmedicSchema = Joi.object().keys({
  zulassung: Joi.string().length(5).regex(/[0-9]/g).required(),
  sequenz: Joi.string().min(1).max(2).regex(/[1-9]/g).required(),
  name: Joi.string().required(),
  hersteller: Joi.string().required(),
  itnummer: Joi.string().regex(/[0-9][0-9]\.[0-9][0-9]\./g).required(),
  atc: Joi.any().allow(atcCodes),
  // ...
  gueltigkeitsdatum: Joi.date("DD.M.YYYY")
  // ...
}});
```

Then you can validate the data within a loop:

```javascript

var swissmedicData = require("data/release/swissmedic/swissmedic.json");
var results = [], i = 0;

for(i; i < swissmedicData.length; i++) {
   results.push(Joi.validate(swissmedicData[i], swissmedicSchema, {abortEarly: false}))
}

```

A ```result.error``` would look like this: 

```javascript
[ {
  message: '"zulassung" length must be 5 characters long',
  path: 'zulassung',
  type: 'string.length',
  context: [Object] 
  },  { 
  message: '"name" is required',
  path: 'name',
  type: 'any.required',
  context: [Object] 
}]
```

Downside of Joy is that it is not possible to pass any custom functions or custom messages. However you can always wrap that, like suggested [here](https://github.com/hapijs/joi/issues/546#issuecomment-73485863).
Maybe this is fair-enough or maybe there is a better more flexible module. 

@meaku & @Jonas74 do you have any thoughts on this?

**Comment by ephaee** [comment]
How about using the JSON Schema standard? There are a few Node.js validation libraries for it. 

OTOH: how about using mocha/chai/expect to test the data?

**Comment by meaku** [comment]
:+1: for JSONSchema

**Comment by topa** [comment]
Yes, something like this would be nice. There are also a bunch of implementations: http://json-schema.org/implementations.html. 
I think one of the most important requirements for a lib is custom or very expressive error messages.

**Comment by ephaee** [comment]
In my personal opinion the only advantage of JSON schema is that it is a standard and there are different libs that could be used. I kind of like the idea of testing the data with mocha or chai that way we'd have nice error messages. What do you think?

**Comment by topa** [comment]
I think this is an option as well, but I'm not sure if it is possible to implement this:
Basically you'll need reference data and a new set of data. Both must me some kind of a map. At least you must be able to identify a set of data.
Than you'll just iterate over both data sets and do `deep.equal`-assertions. This will print 

> nice error messages.

as you've said. But I think it will stop after the first assertions has failed. A quick prototype could check this.
Nevertheless the basic idea is to make a deep equal comparison. *chai* surely uses a library for this, as it is not a simple task because of potential nested objects or rather references.
So I think it would be a quite good approach to use this or a similar lib while iterating and write differences in a log away. 
This is quite simple. 
An advantage over a simple comparison-tool of using a JSON-Schema or a validation lib based on this standard, would be quite precise error messages. A disadvantage is surely that you'll need more lines of code.
Let's follow the simpler idea and check if it really fits the needs.

**Comment by topa** [comment]
I think the logs from #34 BAG-History an #1 Swissmedic-History will do for now. So I close this issue at least for now.
