### ISSUE TITLE
Emil.js: Promise is not defined 

### ISSUE THREAD

**Issue by aspergatus** [epha/robot#42]
Hi Topa

Could you please have a look at emil.js:
ReferenceError: Promise is not defined

Thanks
Tony

**Comment by aspergatus** [comment]
My fault, I used 0.10 of nodejs.

**Comment by topa** [comment]
:+1: 

If it must run on on v0.10.x than we can think about using a polyfill, like this: [promise-polifll](https://github.com/taylorhakes/promise-polyfill).
